version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_drone
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ganesh
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql

  transport:
    build:
      context: .
      dockerfile: Dockerfile
    image: transport
    container_name: transport
    ports:
      - "9092:9092"
    links:
      - postgres:postgres
    volumes:
      - transport_data:/home/img
    environment:
      spring.datasource.url: jdbc:postgresql://postgres/drone
      spring.datasource.username: postgres
      spring.datasource.password: ganesh

volumes:
  postgres_data:
  transport_data: